### ISSUE TITLE
when I click the button to page 2 the error address already in use appears

### ISSUE THREAD

**Issue by bobwatcherx** [SKbarbon/flet_multi_page#1]
code
```
from flet_multi_page import subPage
import flet

def main (page:flet.Page):
    def start_new_page (e):
        p = subPage(controls=[flet.Text("Hello from the new page!!")], page_props={"bgcolor":"blue"})
        p.start()
    
    page.add(flet.ElevatedButton("start new page", on_click=start_new_page))
    page.update()
```

if __name__ == "__main__": #? This is so important, there will be errors without it.
    flet.app(target=main)

root@mino-HP-Convertible-x360-11-ab1XX:/home/mino/belajar/fletmultiwindow# flet --version
0.5.2

error 
```
root@mino-HP-Convertible-x360-11-ab1XX:/home/mino/belajar/fletmultiwindow# flet main.py 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flet_multi_page/sub_page.py", line 27, in _s_
    flet.app(target=APP)
  File "/usr/local/lib/python3.10/dist-packages/flet/flet.py", line 85, in app
    __app_sync(
  File "/usr/local/lib/python3.10/dist-packages/flet/flet.py", line 114, in __app_sync
    conn = __connect_internal_sync(
  File "/usr/local/lib/python3.10/dist-packages/flet/flet.py", line 331, in __connect_internal_sync
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/flet/sync_local_socket_connection.py", line 61, in connect
    self.__sock.bind(self.__uds_path)
OSError: [Errno 98] Address already in use
```

**Comment by SKbarbon** [comment]
Its not `if name == "main"` its `if __name__ == "__main__", Are you sure you did it this way ?

```python
if __name__ == "__main__":
	app(target=main)
```

**Comment by SKD8** [comment]
i got module not found error. whereas i have already imported it via pip. how to resolve ?
![image](https://github.com/user-attachments/assets/8d5d308d-3a02-43d3-b9a0-c23c317d9db1)
